config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'festivals#index'
  
  resources :users
  resources :comments
  resources :artists
  resources :festivals, only: [:index, :show, :edit] do
    resources :festivaldays do
      resources :mytimetables
    end
  end
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :stage, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :festival_id, presence: true
  validates :comment, presence: true
  
  belongs_to :user
  belongs_to :festival
end

app/models/festival.rb
class Festival < ApplicationRecord
  has_many :comments
  has_many :festivaldays
end

app/models/festivalday.rb
class Festivalday < ApplicationRecord
  belongs_to :festival, optional: true
  has_many :stages
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :festivaldays, optional: true
  has_many :artists
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
  validates :email, presence: true
  
  has_secure_password
  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @festivals = Festival.all
    @artists = Artist.all
  end
  
  def new
    @artist = Artist.new
  end
  
  def create
    @artist = Artist.new(artist_params)
    
      if @artist.save
        render :new
      else
        render :new
      end
  end
  
  def edit
    @artist = Artist.find(params[:id])
  end
  
  def destroy
    artist = Artist.find(params[:id])
    
    artist.destroy
  
    redirect_to artists_path
  end
  
  def update
    @artist = Artist.find(params[:id])
  
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      redirect_to artists_path
    end
  end
  
  private
  
  def artist_params
    params.require(:artist).permit(:name, :stage_id, :starttime, :endtime, :appearancetime, :totalstarttime)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
  
  def show
  end
  
  def create
    @comment = current_user.comments.new(comment_params)
    
    if @comment.save
      redirect_to festival_path(@comment.festival.id, anchor: 'comment-keep')
      '投稿に成功しました'
    else
      redirect_to festival_path(@comment.festival.id, anchor: 'comment-keep')
    end
  end
  
  def destroy
    
    comment = Comment.find(params[:id])
    festival_id = comment.festival_id
    comment.destroy
  
    redirect_to festival_path(festival_id, anchor: 'comment-keep')
    
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
  
    if @comment.update(comment_params)
      redirect_to festivals_path(@comment.festival.id, anchor: 'comment-keep')
    else
      render :new
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment, :festival_id)
  end
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  def index
    @festivals = Festival.all
    
    
    if !params[:artist_id].nil?
      @artist = Artist.find(params[:artist_id])
    else
      @artist = nil
    end
  end

  def show
    @festival = Festival.find(params[:id])
    @festivals = Festival.all
    @comment = Comment.new
    @festivaldays = Festivalday.where(festival_id: @festival.id)
  end
  
  
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/mytimetables_controller.rb
class MytimetablesController < ApplicationController
  def show
    @festival = Festival.find(params[:id])
    @festivalday = Festivalday.find(params[:festivalday_id])
    @festivaldays = Festivalday.where(festival_id: @festival.id)
    @stages = Stage.where(festivalday_id: @festivalday.id)
  end
  
  def index
    # checked_artist_ids = []
    # params[:artist_ids].each do |k, v|
    #   if v == "1"
    #     checked_artist_ids << k
    #   end
    # end
    # @artists = Artist.where(id: checked_artist_ids)
    
    # @festival = Festival.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/mytimetables_helper.rb
module MytimetablesHelper
  def computedTableBodyHeight
    @festival.totaltime * 160
  end

  def computedTableItemHeight(appearancetime)
    appearancetime * 160
  end

  def computedTableItemAlign(starttime)
    starttime * 100 / @festival.totaltime
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/edit.html.erb
<div class="title">
  <h1>artist編集</h1>
  <%= form_for @artist do |f| %>
  <%= f.text_field :name %>
        <%= f.submit "更新" %>
  <% end %>
</div>

app/views/artists/index.html.erb
<div class="title">
  <h1>Artists#index</h1>
</div>

<% @artists.each do |artist| %>
  <%= artist.id %>：<%= artist.name %>：<%= artist.stage_id %>：<%= artist.starttime %>：<%= artist.endtime %>：<%= artist.appearancetime %>：<%= artist.totalstarttime %>
  <%= link_to "削除", artist_path(artist.id), method: :delete %>
  <%= link_to "編集", edit_artist_path(artist.id) %>
  <br>
<% end %>

app/views/artists/new.html.erb
<div class="title">
  <h1>artist登録ページ</h1>
</div>

<%= form_for @artist do |f| %>
  <p>
    <%= f.label :name, "artist name" %><br>
    <%= f.text_field :name %><br>
    <%= f.label :stage_id, "stage_id" %><br>
    <%= f.text_field :stage_id %><br>
    <%= f.label :starttime, "starttime" %><br>
    <%= f.text_field :starttime %><br>
    <%= f.label :endtime, "endtime" %><br>
    <%= f.text_field :endtime %><br>
    <%= f.label :appearancetime, "appearancetime" %><br>
    <%= f.text_field :appearancetime %><br>
    <%= f.label :totalstarttime, "totalstarttime" %><br>
    <%= f.text_field :totalstarttime %><br>
  </p>
  <%= f.submit "登録する"%>
<% end %>

<%= link_to "artist一覧" ,artists_path %>

app/views/comments/edit.html.erb
<div class="title">
  <h1>コメント編集</h1>
</div>


  <%= form_for @comment do |f| %>
  <%= f.text_field :comment %>
  <%= f.submit "更新" %>
  <% end %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/festivals/index.html.erb
<p>festivalのページです</p>



<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <div class="title">
    <p class="text-white">My Time Table</p>
    </div>
    <br>
    <br>
    <div class="text-white">
    <div class="fes-list"><p>フェス一覧</p></div>
    </div>
    
    <% @festivals.each do |festival| %>
        <%= link_to festival.name , festival_path(festival.id) , class: 'btn btn-block btn-white' %>
    <% end %>
    

    
    <br>
    <br>
    
    <div class="title-mytimetable">
      <h1 class="text-brack">My Time Table</h1>
      <h2 class="text-brack">自分だけのタイムテーブルを作ろう！！</h2>
    </div>

    <div class="Artist-Select">
    <label for="Artist">選択してください</label>
    <select id="festivals">
      <option value="rock in japan festival">ROCK IN JAPAN FESTIVAL</option>
      <option value="rising sun rock festival">RISING SUN ROCK FESTIVAL</option>
      <option value="fuji rock festival">FUJI ROCK FESTIVAL</option>
      <option value="summer sonic">SUMMER SONIC</option>
      <option value="countdown japan">COUNTDOWN JAPAN</option>
      <option value="radio crazy">RADIO CRAZY</option>
      <option value="viva la rock">VIVA LA ROCK</option>
      <option value="japan jam">JAPAN JAM</option>
      <option value="metropolitan rock festival">METROPOLITAN ROCK FESTIVAL</option>
    </select>
    
    

    
    </div>

    <script>
      let selector = document.querySelector('#festivals');
      selector.addEventListener('change', (event) => {
      let box = document.querySelector('#box');
      box.textContent = event.target.value;
    });
    </script>
    
    <div class="input-mytimetable">
    
    <div id="box"></div>


    
    
    <div id="input_pluralBox">
      <div id="input_plural">
        
    
    <div class="row">
      <form action="/sample" method="post">
      <div class="col-md-4">
        <table>
          <tr>
            <div class="Time-title">
            <label>time</label><br>
              <div class="Time-select">
                <th><input type="time" name="smp01" class="time-title" value="10:00" style="font-size:40px;"></th>
              </div>
            </div>
          </tr>
        </table>
      </div>
      <div class="col-md-4">
        <div class="Artist-title">
          <p>Artist<br>
          <% if !@artist.nil? %>
            <p><%= @artist.name %></p>
          <% end %>
           <%= link_to 'アーティスト', artists_path %></p>
        </div>
      </div>
       <div class="col-md-4">
        <div class="Stage-title">
          <p>Stage<br>
          <input type="text" name="name" class="stage-title"></p>
        </div>
      </div>
    </div>
    
      </div>
    </div>
    
    <input type="button" value="＋" class="add pluralBtn">
    <input type="button" value="－" class="del pluralBtn">
    
    <script type="text/javascript">
    $(document).on("click", ".add", function() {
        $(this).parent().clone(true).insertAfter($(this).parent());
    });
    $(document).on("click", ".del", function() {
        var target = $(this).parent();
        if (target.parent().children().length > 1) {
            target.remove();
        }
    });
    </script>
    
    
    
    <script>
      
    </script>
  </div>
</div>
</div>
<h1 class="text-brack">
  <%= link_to "artist登録" , new_artist_path, class: 'btn btn-block btn-brack' %>
</h1>

app/views/festivals/show.html.erb
<div class="festival-index-wrapper">
    <div class="title">
        <p class="text-brack text-festival"><%= @festival.name %></p>
    </div>
    <br>

    <div class="festival-image">
        <img src="/assets/<%= @festival.name %>.jpg" alt="">
    </div>
    <br>
    <div class="festival-toha">
        <p><%= @festival.name %>とは？</p>
    </div>
    <br>
    <div class="festival-overview">
        <span class="box-title">概要</span>
        <p>データベースに追加...</p>
    </div>
    
    <div class="festival-place">
        <span class="box-place">場所</span>
        <p>データベースに追加...</p>
    </div>
    
    <div class="festival-feature">
        <span class="box-feature">特徴</span>
        <p>データベースに追加...</p>
    </div>

    <div class="festival-comment-title">
        <p>コメント</p>
    </div>
    
    <div class="festival-comment-list" id="comment-keep">
        <% @festival.comments.each do |comment| %>
            <div class="comment-left">
            <p><%= comment.user.name %> ： <%=  comment.comment %>　
                <% if current_user == comment.user %>
                    <%= link_to "削除", comment_path(comment.id), method: :delete %>
                    <%= link_to "編集", edit_comment_path(comment.id) %>
                <% end %>
            </p>
            </div>
                
        <% end %>
    </div>
    
    <br>
    
    <div class="festivalname-and-username">
        <p>フェス名：「<%= @festival.name %>」</p>
        <% if current_user %>
            <p>ユーザー名：「<%= current_user.name %>」</p>
        <% else %>
            <p>ユーザー名：「ゲストユーザー」</p>
        <% end %>
    </div>
    
    <% if current_user %>
    <%= form_for @comment do |f| %>
    <div class="festival-comment">
        <%= f.hidden_field :festival_id, value: @festival.id %>
        <%= f.text_field :comment %>
        <%= f.submit "送信" %>
    </div>
    <% end %>
    <% else %>
        <br>
        <p>※コメントするにはログインしてください。</p>
    <% end %>

    <div class="mytimetable-create-title">
        <p>タイムテーブル作成</p>
    </div>
    
    <p>日付</p>
        <% @festival.festivaldays.each do |festivalday| %>
            <%= link_to festivalday.date, festival_festivalday_mytimetable_path(@festival.id, festivalday.id )  , class: 'btn btn-block btn-white' %>
        <% end %>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>